const items = {
  "Dairy": [
    "Milk",
    "Eggs",
    "Cheese",
    "Butter",
    "Yogurt",
    "Ice Cream",
    "Whipped Cream",
  ],
  "Baking": [
    "Flour",
    "Sugar",
    "Salt",
    "Baking Powder",
    "Baking Soda",
    "Vanilla",
    "Cinnamon",
    "Nutmeg",
    "Cocoa Powder",
    "Chocolate Chips"
  ],
  "Breads & Bakery": [
    "Bread",
    "Bagels",
    "English Muffins",
    "Pita Bread",
    "Tortillas",
    "Pizza Dough",
    "Cinnamon Rolls",
    "Donuts",
    "Croissants",
    "Buns",
    "Biscuits"
  ],
  "Meat": [
    "Beef",
    "Pork",
    "Chicken",
    "Turkey",
    "Lamb",
    "Fish",
    "Sausage",
    "Bacon",
    "Ham",
    "Hot Dogs"
  ],
  "Fruits": [
    "Apples",
    "Oranges",
    "Bananas",
    "Grapes",
    "Strawberries",
    "Blueberries",
    "Raspberries",
    "Blackberries",
    "Pineapple",
    "Watermelon",
    "Mango",
    "Peaches",
    "Nectarines"
  ],
  "Vegetables": [
    "Potatoes",
    "Carrots",
    "Onions",
    "Garlic",
    "Tomatoes",
    "Lettuce",
    "Spinach",
    "Broccoli",
    "Cauliflower",
    "Peas",
    "Corn",
    "Green Beans"
  ],
  "Snacks": [
    "Chips",
    "Cookies",
    "Candy",
    "Crackers",
    "Popcorn",
    "Pretzels",
    "Nuts",
    "Trail Mix",
    "Granola Bars",
    "Fruit Snacks",
    "Dried Fruit"
  ],
  "Beverages": [
    "Alcohol",
    "Water",
    "Soda",
    "Juice",
    "Milk",
    "Coffee",
    "Tea",
    "Hot Chocolate",
    "Sports Drinks",
    "Energy Drinks"
  ]
}